name: CI/CD for userandauthservice

on:
  push:
    branches: [ "*" ]
    paths:
      - 'userandauthservice/**'
  pull_request:
    branches: [ "*" ]
    paths:
      - 'userandauthservice/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build userandauthservice
        run: mvn -B package --file userandauthservice/pom.xml

  analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: userandauthservice
          args: >
            -Dsonar.projectKey=userandauthservice
            -Dsonar.organization=springbootchatapp
